"""Initial PostgreSQL schema, frozen independently of ORM metadata."""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision = "0001_initial"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("email", sa.String(length=254), nullable=False),
        sa.Column("password_hash", sa.Text(), nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "email = lower(trim(email)) AND length(email) > 0",
            name=op.f("ck_users_email_normalized"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("email", name=op.f("uq_users_email")),
    )
    op.create_table(
        "projects",
        sa.Column("owner_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("description", sa.String(length=500), nullable=True),
        sa.Column("public_slug", sa.String(length=80), nullable=False),
        sa.Column(
            "public_status_enabled", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column("revision", sa.BigInteger(), server_default=sa.text("0"), nullable=False),
        sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("revision >= 0", name=op.f("ck_projects_revision_nonnegative")),
        sa.ForeignKeyConstraint(
            ["owner_id"], ["users.id"], name=op.f("fk_projects_owner_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_projects")),
        sa.UniqueConstraint("public_slug", name=op.f("uq_projects_public_slug")),
    )
    op.create_index(
        "ix_projects_owner_active",
        "projects",
        ["owner_id", "created_at", "id"],
        unique=False,
        postgresql_where=sa.text("archived_at IS NULL"),
        sqlite_where=sa.text("archived_at IS NULL"),
    )
    op.create_table(
        "sessions",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("token_hash", sa.Text(), nullable=False),
        sa.Column("csrf_token", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "expires_at > created_at", name=op.f("ck_sessions_expiry_after_creation")
        ),
        sa.CheckConstraint(
            "last_seen_at >= created_at", name=op.f("ck_sessions_seen_after_creation")
        ),
        sa.CheckConstraint(
            "revoked_at IS NULL OR revoked_at >= created_at",
            name=op.f("ck_sessions_revoked_after_creation"),
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], name=op.f("fk_sessions_user_id_users")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sessions")),
        sa.UniqueConstraint("token_hash", name=op.f("uq_sessions_token_hash")),
    )
    op.create_index("ix_sessions_expires_at", "sessions", ["expires_at"], unique=False)
    op.create_index("ix_sessions_user_revoked", "sessions", ["user_id", "revoked_at"], unique=False)
    op.create_table(
        "monitors",
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("url", sa.String(length=2048), nullable=False),
        sa.Column("method", sa.Text(), server_default=sa.text("'GET'"), nullable=False),
        sa.Column("interval_seconds", sa.Integer(), server_default=sa.text("60"), nullable=False),
        sa.Column("timeout_ms", sa.Integer(), server_default=sa.text("5000"), nullable=False),
        sa.Column(
            "expected_status", sa.SmallInteger(), server_default=sa.text("200"), nullable=False
        ),
        sa.Column(
            "failure_threshold", sa.SmallInteger(), server_default=sa.text("3"), nullable=False
        ),
        sa.Column("retry_count", sa.SmallInteger(), server_default=sa.text("1"), nullable=False),
        sa.Column(
            "latency_threshold_ms", sa.Integer(), server_default=sa.text("1000"), nullable=True
        ),
        sa.Column("config_version", sa.BigInteger(), server_default=sa.text("1"), nullable=False),
        sa.Column("paused_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_public", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("next_check_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("health_status", sa.Text(), nullable=True),
        sa.Column(
            "consecutive_failures", sa.Integer(), server_default=sa.text("0"), nullable=False
        ),
        sa.Column("first_failure_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_checked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_scheduled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_http_status", sa.SmallInteger(), nullable=True),
        sa.Column("last_latency_ms", sa.Double(), nullable=True),
        sa.Column("last_outcome", sa.Text(), nullable=True),
        sa.Column("last_error_code", sa.Text(), nullable=True),
        sa.Column("last_degradation_reason", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "health_status IN ('online', 'degraded', 'offline')",
            name=op.f("ck_monitors_health_status_values"),
        ),
        sa.CheckConstraint(
            "last_degradation_reason IN ('failure_pending', 'retry_recovered', 'high_latency')",
            name=op.f("ck_monitors_degradation_values"),
        ),
        sa.CheckConstraint(
            "last_error_code IN ('timeout', 'dns_error', 'connection_error', 'tls_error', 'unexpected_status')",
            name=op.f("ck_monitors_error_values"),
        ),
        sa.CheckConstraint(
            "last_outcome IN ('success', 'failure')", name=op.f("ck_monitors_outcome_values")
        ),
        sa.CheckConstraint("method = 'GET'", name=op.f("ck_monitors_method_get")),
        sa.CheckConstraint(
            "(paused_at IS NULL AND archived_at IS NULL) OR next_check_at IS NULL",
            name=op.f("ck_monitors_inactive_unscheduled"),
        ),
        sa.CheckConstraint(
            "(retry_count + 1) * timeout_ms + CASE retry_count WHEN 0 THEN 0 WHEN 1 THEN 600 ELSE 1800 END + 3000 <= 50000",
            name=op.f("ck_monitors_cycle_budget"),
        ),
        sa.CheckConstraint("config_version >= 1", name=op.f("ck_monitors_config_version_positive")),
        sa.CheckConstraint(
            "consecutive_failures >= 0", name=op.f("ck_monitors_failures_nonnegative")
        ),
        sa.CheckConstraint(
            "expected_status BETWEEN 200 AND 599", name=op.f("ck_monitors_expected_status_range")
        ),
        sa.CheckConstraint(
            "failure_threshold BETWEEN 1 AND 10", name=op.f("ck_monitors_failure_threshold_range")
        ),
        sa.CheckConstraint(
            "interval_seconds BETWEEN 60 AND 3600", name=op.f("ck_monitors_interval_range")
        ),
        sa.CheckConstraint(
            "last_http_status BETWEEN 200 AND 599", name=op.f("ck_monitors_last_http_status_range")
        ),
        sa.CheckConstraint(
            "last_latency_ms >= 0", name=op.f("ck_monitors_last_latency_nonnegative")
        ),
        sa.CheckConstraint(
            "latency_threshold_ms IS NULL OR (latency_threshold_ms BETWEEN 100 AND 15000 AND latency_threshold_ms <= timeout_ms)",
            name=op.f("ck_monitors_latency_threshold_range"),
        ),
        sa.CheckConstraint(
            "retry_count BETWEEN 0 AND 2", name=op.f("ck_monitors_retry_count_range")
        ),
        sa.CheckConstraint(
            "timeout_ms BETWEEN 1000 AND 15000", name=op.f("ck_monitors_timeout_range")
        ),
        sa.ForeignKeyConstraint(
            ["project_id"], ["projects.id"], name=op.f("fk_monitors_project_id_projects")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_monitors")),
    )
    op.create_index(
        "ix_monitors_due",
        "monitors",
        ["next_check_at", "id"],
        unique=False,
        postgresql_where=sa.text("paused_at IS NULL AND archived_at IS NULL"),
        sqlite_where=sa.text("paused_at IS NULL AND archived_at IS NULL"),
    )
    op.create_index(
        "ix_monitors_project_created", "monitors", ["project_id", "created_at", "id"], unique=False
    )
    op.create_table(
        "check_jobs",
        sa.Column("monitor_id", sa.Uuid(), nullable=False),
        sa.Column("config_version", sa.BigInteger(), nullable=False),
        sa.Column(
            "config_snapshot",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("scheduled_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("budget_ms", sa.Integer(), nullable=False),
        sa.Column("skipped_slots", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("status", sa.Text(), server_default=sa.text("'pending'"), nullable=False),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("retry_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("lease_token", sa.Uuid(), nullable=True),
        sa.Column("lease_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "execution_count", sa.SmallInteger(), server_default=sa.text("0"), nullable=False
        ),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("error_code", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status != 'running' OR (lease_token IS NOT NULL AND started_at IS NOT NULL AND execution_count >= 1)",
            name=op.f("ck_check_jobs_running_lease"),
        ),
        sa.CheckConstraint(
            "status IN ('pending', 'running') OR (finished_at IS NOT NULL AND lease_token IS NULL)",
            name=op.f("ck_check_jobs_terminal_finished"),
        ),
        sa.CheckConstraint(
            "status IN ('pending', 'running', 'completed', 'expired', 'cancelled', 'exhausted')",
            name=op.f("ck_check_jobs_status_values"),
        ),
        sa.CheckConstraint(
            "(lease_token IS NULL) = (lease_expires_at IS NULL)",
            name=op.f("ck_check_jobs_lease_pair"),
        ),
        sa.CheckConstraint(
            "budget_ms BETWEEN 1 AND 50000", name=op.f("ck_check_jobs_budget_range")
        ),
        sa.CheckConstraint(
            "config_version >= 1", name=op.f("ck_check_jobs_config_version_positive")
        ),
        sa.CheckConstraint(
            "execution_count BETWEEN 0 AND 3", name=op.f("ck_check_jobs_execution_count_range")
        ),
        sa.CheckConstraint(
            "expires_at > scheduled_at", name=op.f("ck_check_jobs_expiry_after_schedule")
        ),
        sa.CheckConstraint(
            "finished_at IS NULL OR finished_at >= scheduled_at",
            name=op.f("ck_check_jobs_finished_after_schedule"),
        ),
        sa.CheckConstraint("skipped_slots >= 0", name=op.f("ck_check_jobs_skipped_nonnegative")),
        sa.ForeignKeyConstraint(
            ["monitor_id"], ["monitors.id"], name=op.f("fk_check_jobs_monitor_id_monitors")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_check_jobs")),
        sa.UniqueConstraint(
            "id",
            "monitor_id",
            "config_version",
            "scheduled_at",
            name="uq_check_jobs_result_identity",
        ),
        sa.UniqueConstraint(
            "monitor_id", "config_version", "scheduled_at", name="uq_check_jobs_cycle"
        ),
    )
    op.create_index("ix_check_jobs_finished_at", "check_jobs", ["finished_at"], unique=False)
    op.create_index(
        "ix_check_jobs_monitor_schedule",
        "check_jobs",
        ["monitor_id", "scheduled_at", "id"],
        unique=False,
    )
    op.create_index(
        "ix_check_jobs_open_expiry",
        "check_jobs",
        ["expires_at"],
        unique=False,
        postgresql_where=sa.text("status IN ('pending', 'running')"),
        sqlite_where=sa.text("status IN ('pending', 'running')"),
    )
    op.create_index(
        "ix_check_jobs_pending_publish",
        "check_jobs",
        ["retry_at", "published_at", "scheduled_at"],
        unique=False,
        postgresql_where=sa.text("status = 'pending'"),
        sqlite_where=sa.text("status = 'pending'"),
    )
    op.create_index(
        "ix_check_jobs_running_lease",
        "check_jobs",
        ["lease_expires_at"],
        unique=False,
        postgresql_where=sa.text("status = 'running'"),
        sqlite_where=sa.text("status = 'running'"),
    )
    op.create_index(
        "uq_check_jobs_open_monitor",
        "check_jobs",
        ["monitor_id"],
        unique=True,
        postgresql_where=sa.text("status IN ('pending', 'running')"),
        sqlite_where=sa.text("status IN ('pending', 'running')"),
    )
    op.create_table(
        "check_results",
        sa.Column("job_id", sa.Uuid(), nullable=False),
        sa.Column("monitor_id", sa.Uuid(), nullable=False),
        sa.Column("config_version", sa.BigInteger(), nullable=False),
        sa.Column("scheduled_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("outcome", sa.Text(), nullable=False),
        sa.Column("http_status", sa.SmallInteger(), nullable=True),
        sa.Column("latency_ms", sa.Double(), nullable=True),
        sa.Column("cycle_duration_ms", sa.Double(), nullable=False),
        sa.Column("queue_delay_ms", sa.Double(), nullable=False),
        sa.Column("attempt_count", sa.SmallInteger(), nullable=False),
        sa.Column(
            "attempts",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("error_code", sa.Text(), nullable=True),
        sa.Column("health_after", sa.Text(), nullable=False),
        sa.Column("degradation_reason", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "degradation_reason IN ('failure_pending', 'retry_recovered', 'high_latency')",
            name=op.f("ck_check_results_degradation_values"),
        ),
        sa.CheckConstraint(
            "error_code IN ('timeout', 'dns_error', 'connection_error', 'tls_error', 'unexpected_status')",
            name=op.f("ck_check_results_error_values"),
        ),
        sa.CheckConstraint(
            "health_after IN ('online', 'degraded', 'offline')",
            name=op.f("ck_check_results_health_values"),
        ),
        sa.CheckConstraint(
            "outcome != 'success' OR (http_status IS NOT NULL AND latency_ms IS NOT NULL AND error_code IS NULL)",
            name=op.f("ck_check_results_success_response"),
        ),
        sa.CheckConstraint(
            "outcome IN ('success', 'failure')", name=op.f("ck_check_results_outcome_values")
        ),
        sa.CheckConstraint(
            "attempt_count BETWEEN 1 AND 3", name=op.f("ck_check_results_attempt_count_range")
        ),
        sa.CheckConstraint(
            "cycle_duration_ms >= 0 AND queue_delay_ms >= 0",
            name=op.f("ck_check_results_durations_nonnegative"),
        ),
        sa.CheckConstraint(
            "http_status BETWEEN 200 AND 599", name=op.f("ck_check_results_http_status_range")
        ),
        sa.CheckConstraint("latency_ms >= 0", name=op.f("ck_check_results_latency_nonnegative")),
        sa.CheckConstraint(
            "scheduled_at <= started_at AND started_at <= completed_at",
            name=op.f("ck_check_results_temporal_order"),
        ),
        sa.ForeignKeyConstraint(
            ["job_id", "monitor_id", "config_version", "scheduled_at"],
            [
                "check_jobs.id",
                "check_jobs.monitor_id",
                "check_jobs.config_version",
                "check_jobs.scheduled_at",
            ],
            name="fk_check_results_job_identity",
        ),
        sa.ForeignKeyConstraint(
            ["monitor_id"], ["monitors.id"], name=op.f("fk_check_results_monitor_id_monitors")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_check_results")),
        sa.UniqueConstraint("job_id", name=op.f("uq_check_results_job_id")),
    )
    op.create_index(
        "ix_check_results_completed_at", "check_results", ["completed_at"], unique=False
    )
    op.create_index(
        "ix_check_results_history",
        "check_results",
        ["monitor_id", sa.literal_column("scheduled_at DESC"), sa.literal_column("id DESC")],
        unique=False,
    )
    op.create_table(
        "incidents",
        sa.Column("monitor_id", sa.Uuid(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("detected_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ended_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("end_reason", sa.Text(), nullable=True),
        sa.Column("opening_check_id", sa.Uuid(), nullable=True),
        sa.Column("closing_check_id", sa.Uuid(), nullable=True),
        sa.Column("cause_code", sa.Text(), nullable=False),
        sa.Column("failure_threshold_snapshot", sa.SmallInteger(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "cause_code IN ('timeout', 'dns_error', 'connection_error', 'tls_error', 'unexpected_status')",
            name=op.f("ck_incidents_cause_values"),
        ),
        sa.CheckConstraint(
            "end_reason IN ('recovered', 'configuration_changed', 'archived')",
            name=op.f("ck_incidents_end_reason_values"),
        ),
        sa.CheckConstraint(
            "(ended_at IS NULL) = (end_reason IS NULL)", name=op.f("ck_incidents_end_pair")
        ),
        sa.CheckConstraint(
            "failure_threshold_snapshot BETWEEN 1 AND 10", name=op.f("ck_incidents_threshold_range")
        ),
        sa.CheckConstraint(
            "started_at <= detected_at AND (ended_at IS NULL OR detected_at <= ended_at)",
            name=op.f("ck_incidents_temporal_order"),
        ),
        sa.ForeignKeyConstraint(
            ["closing_check_id"],
            ["check_results.id"],
            name=op.f("fk_incidents_closing_check_id_check_results"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["monitor_id"], ["monitors.id"], name=op.f("fk_incidents_monitor_id_monitors")
        ),
        sa.ForeignKeyConstraint(
            ["opening_check_id"],
            ["check_results.id"],
            name=op.f("fk_incidents_opening_check_id_check_results"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_incidents")),
    )
    op.create_index("ix_incidents_ended_at", "incidents", ["ended_at"], unique=False)
    op.create_index(
        "ix_incidents_history",
        "incidents",
        ["monitor_id", sa.literal_column("started_at DESC"), sa.literal_column("id DESC")],
        unique=False,
    )
    op.create_index(
        "uq_incidents_open_monitor",
        "incidents",
        ["monitor_id"],
        unique=True,
        postgresql_where=sa.text("ended_at IS NULL"),
        sqlite_where=sa.text("ended_at IS NULL"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "uq_incidents_open_monitor",
        table_name="incidents",
        postgresql_where=sa.text("ended_at IS NULL"),
        sqlite_where=sa.text("ended_at IS NULL"),
    )
    op.drop_index("ix_incidents_history", table_name="incidents")
    op.drop_index("ix_incidents_ended_at", table_name="incidents")
    op.drop_table("incidents")
    op.drop_index("ix_check_results_history", table_name="check_results")
    op.drop_index("ix_check_results_completed_at", table_name="check_results")
    op.drop_table("check_results")
    op.drop_index(
        "uq_check_jobs_open_monitor",
        table_name="check_jobs",
        postgresql_where=sa.text("status IN ('pending', 'running')"),
        sqlite_where=sa.text("status IN ('pending', 'running')"),
    )
    op.drop_index(
        "ix_check_jobs_running_lease",
        table_name="check_jobs",
        postgresql_where=sa.text("status = 'running'"),
        sqlite_where=sa.text("status = 'running'"),
    )
    op.drop_index(
        "ix_check_jobs_pending_publish",
        table_name="check_jobs",
        postgresql_where=sa.text("status = 'pending'"),
        sqlite_where=sa.text("status = 'pending'"),
    )
    op.drop_index(
        "ix_check_jobs_open_expiry",
        table_name="check_jobs",
        postgresql_where=sa.text("status IN ('pending', 'running')"),
        sqlite_where=sa.text("status IN ('pending', 'running')"),
    )
    op.drop_index("ix_check_jobs_monitor_schedule", table_name="check_jobs")
    op.drop_index("ix_check_jobs_finished_at", table_name="check_jobs")
    op.drop_table("check_jobs")
    op.drop_index("ix_monitors_project_created", table_name="monitors")
    op.drop_index(
        "ix_monitors_due",
        table_name="monitors",
        postgresql_where=sa.text("paused_at IS NULL AND archived_at IS NULL"),
        sqlite_where=sa.text("paused_at IS NULL AND archived_at IS NULL"),
    )
    op.drop_table("monitors")
    op.drop_index("ix_sessions_user_revoked", table_name="sessions")
    op.drop_index("ix_sessions_expires_at", table_name="sessions")
    op.drop_table("sessions")
    op.drop_index(
        "ix_projects_owner_active",
        table_name="projects",
        postgresql_where=sa.text("archived_at IS NULL"),
        sqlite_where=sa.text("archived_at IS NULL"),
    )
    op.drop_table("projects")
    op.drop_table("users")
    # ### end Alembic commands ###
